; Listing generated by Microsoft (R) Optimizing Compiler Version 19.40.33812.0 

	TITLE	C:\Users\Vova\source\repos\RGZ_ABC\RGZ_ABC.obj
	.686P
	.XMM
	; include listing.inc
	.model	flat
	assume fs:nothing

; INCLUDELIB LIBCMT
; INCLUDELIB OLDNAMES

PUBLIC	?get_module_by_name@@YAPAXPA_W@Z		; get_module_by_name
PUBLIC	?get_func_by_name@@YAPAXPAXPAD@Z		; get_func_by_name
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
__system$ = -184					; size = 4
_msgBoxID$ = -180					; size = 4
_shell32_base$ = -176					; size = 4
_k32_dll$ = -172					; size = 26
_title_text$ = -144					; size = 10
_msg_text$ = -132					; size = 6
_msvcrt_base$ = -124					; size = 4
__MessageBoxW$ = -120					; size = 4
_user32_base$ = -116					; size = 4
_shellexecute_func$ = -112				; size = 14
__GetProcAddress$ = -96					; size = 4
_kernel32_base$ = -92					; size = 4
_get_proc$ = -88					; size = 15
_load_lib$ = -72					; size = 13
_msgboxw_func$ = -56					; size = 12
_msvcrt_dll$ = -44					; size = 11
_notepad$ = -32						; size = 8
_system_func$ = -24					; size = 7
_u32_dll$ = -16						; size = 11
__LoadLibraryA$ = -4					; size = 4
_main	PROC
; File C:\Users\Vova\source\repos\RGZ_ABC\RGZ_ABC.cpp
; Line 13
	push	ebp
	mov	ebp, esp
	sub	esp, 184				; 000000b8H
; Line 14
	mov	eax, 107				; 0000006bH
	mov	WORD PTR _k32_dll$[ebp], ax
	mov	ecx, 101				; 00000065H
	mov	WORD PTR _k32_dll$[ebp+2], cx
	mov	edx, 114				; 00000072H
	mov	WORD PTR _k32_dll$[ebp+4], dx
	mov	eax, 110				; 0000006eH
	mov	WORD PTR _k32_dll$[ebp+6], ax
	mov	ecx, 101				; 00000065H
	mov	WORD PTR _k32_dll$[ebp+8], cx
	mov	edx, 108				; 0000006cH
	mov	WORD PTR _k32_dll$[ebp+10], dx
	mov	eax, 51					; 00000033H
	mov	WORD PTR _k32_dll$[ebp+12], ax
	mov	ecx, 50					; 00000032H
	mov	WORD PTR _k32_dll$[ebp+14], cx
	mov	edx, 46					; 0000002eH
	mov	WORD PTR _k32_dll$[ebp+16], dx
	mov	eax, 100				; 00000064H
	mov	WORD PTR _k32_dll$[ebp+18], ax
	mov	ecx, 108				; 0000006cH
	mov	WORD PTR _k32_dll$[ebp+20], cx
	mov	edx, 108				; 0000006cH
	mov	WORD PTR _k32_dll$[ebp+22], dx
	xor	eax, eax
	mov	WORD PTR _k32_dll$[ebp+24], ax
; Line 15
	mov	BYTE PTR _u32_dll$[ebp], 117		; 00000075H
	mov	BYTE PTR _u32_dll$[ebp+1], 115		; 00000073H
	mov	BYTE PTR _u32_dll$[ebp+2], 101		; 00000065H
	mov	BYTE PTR _u32_dll$[ebp+3], 114		; 00000072H
	mov	BYTE PTR _u32_dll$[ebp+4], 51		; 00000033H
	mov	BYTE PTR _u32_dll$[ebp+5], 50		; 00000032H
	mov	BYTE PTR _u32_dll$[ebp+6], 46		; 0000002eH
	mov	BYTE PTR _u32_dll$[ebp+7], 100		; 00000064H
	mov	BYTE PTR _u32_dll$[ebp+8], 108		; 0000006cH
	mov	BYTE PTR _u32_dll$[ebp+9], 108		; 0000006cH
	mov	BYTE PTR _u32_dll$[ebp+10], 0
; Line 17
	mov	BYTE PTR _load_lib$[ebp], 76		; 0000004cH
	mov	BYTE PTR _load_lib$[ebp+1], 111		; 0000006fH
	mov	BYTE PTR _load_lib$[ebp+2], 97		; 00000061H
	mov	BYTE PTR _load_lib$[ebp+3], 100		; 00000064H
	mov	BYTE PTR _load_lib$[ebp+4], 76		; 0000004cH
	mov	BYTE PTR _load_lib$[ebp+5], 105		; 00000069H
	mov	BYTE PTR _load_lib$[ebp+6], 98		; 00000062H
	mov	BYTE PTR _load_lib$[ebp+7], 114		; 00000072H
	mov	BYTE PTR _load_lib$[ebp+8], 97		; 00000061H
	mov	BYTE PTR _load_lib$[ebp+9], 114		; 00000072H
	mov	BYTE PTR _load_lib$[ebp+10], 121	; 00000079H
	mov	BYTE PTR _load_lib$[ebp+11], 65		; 00000041H
	mov	BYTE PTR _load_lib$[ebp+12], 0
; Line 18
	mov	BYTE PTR _get_proc$[ebp], 71		; 00000047H
	mov	BYTE PTR _get_proc$[ebp+1], 101		; 00000065H
	mov	BYTE PTR _get_proc$[ebp+2], 116		; 00000074H
	mov	BYTE PTR _get_proc$[ebp+3], 80		; 00000050H
	mov	BYTE PTR _get_proc$[ebp+4], 114		; 00000072H
	mov	BYTE PTR _get_proc$[ebp+5], 111		; 0000006fH
	mov	BYTE PTR _get_proc$[ebp+6], 99		; 00000063H
	mov	BYTE PTR _get_proc$[ebp+7], 65		; 00000041H
	mov	BYTE PTR _get_proc$[ebp+8], 100		; 00000064H
	mov	BYTE PTR _get_proc$[ebp+9], 100		; 00000064H
	mov	BYTE PTR _get_proc$[ebp+10], 114	; 00000072H
	mov	BYTE PTR _get_proc$[ebp+11], 101	; 00000065H
	mov	BYTE PTR _get_proc$[ebp+12], 115	; 00000073H
	mov	BYTE PTR _get_proc$[ebp+13], 115	; 00000073H
	mov	BYTE PTR _get_proc$[ebp+14], 0
; Line 19
	mov	BYTE PTR _msvcrt_dll$[ebp], 109		; 0000006dH
	mov	BYTE PTR _msvcrt_dll$[ebp+1], 115	; 00000073H
	mov	BYTE PTR _msvcrt_dll$[ebp+2], 118	; 00000076H
	mov	BYTE PTR _msvcrt_dll$[ebp+3], 99	; 00000063H
	mov	BYTE PTR _msvcrt_dll$[ebp+4], 114	; 00000072H
	mov	BYTE PTR _msvcrt_dll$[ebp+5], 116	; 00000074H
	mov	BYTE PTR _msvcrt_dll$[ebp+6], 46	; 0000002eH
	mov	BYTE PTR _msvcrt_dll$[ebp+7], 100	; 00000064H
	mov	BYTE PTR _msvcrt_dll$[ebp+8], 108	; 0000006cH
	mov	BYTE PTR _msvcrt_dll$[ebp+9], 108	; 0000006cH
	mov	BYTE PTR _msvcrt_dll$[ebp+10], 0
; Line 20
	mov	BYTE PTR _system_func$[ebp], 115	; 00000073H
	mov	BYTE PTR _system_func$[ebp+1], 121	; 00000079H
	mov	BYTE PTR _system_func$[ebp+2], 115	; 00000073H
	mov	BYTE PTR _system_func$[ebp+3], 116	; 00000074H
	mov	BYTE PTR _system_func$[ebp+4], 101	; 00000065H
	mov	BYTE PTR _system_func$[ebp+5], 109	; 0000006dH
	mov	BYTE PTR _system_func$[ebp+6], 0
; Line 22
	mov	BYTE PTR _msgboxw_func$[ebp], 77	; 0000004dH
	mov	BYTE PTR _msgboxw_func$[ebp+1], 101	; 00000065H
	mov	BYTE PTR _msgboxw_func$[ebp+2], 115	; 00000073H
	mov	BYTE PTR _msgboxw_func$[ebp+3], 115	; 00000073H
	mov	BYTE PTR _msgboxw_func$[ebp+4], 97	; 00000061H
	mov	BYTE PTR _msgboxw_func$[ebp+5], 103	; 00000067H
	mov	BYTE PTR _msgboxw_func$[ebp+6], 101	; 00000065H
	mov	BYTE PTR _msgboxw_func$[ebp+7], 66	; 00000042H
	mov	BYTE PTR _msgboxw_func$[ebp+8], 111	; 0000006fH
	mov	BYTE PTR _msgboxw_func$[ebp+9], 120	; 00000078H
	mov	BYTE PTR _msgboxw_func$[ebp+10], 87	; 00000057H
	mov	BYTE PTR _msgboxw_func$[ebp+11], 0
; Line 23
	mov	BYTE PTR _shellexecute_func$[ebp], 83	; 00000053H
	mov	BYTE PTR _shellexecute_func$[ebp+1], 104 ; 00000068H
	mov	BYTE PTR _shellexecute_func$[ebp+2], 101 ; 00000065H
	mov	BYTE PTR _shellexecute_func$[ebp+3], 108 ; 0000006cH
	mov	BYTE PTR _shellexecute_func$[ebp+4], 108 ; 0000006cH
	mov	BYTE PTR _shellexecute_func$[ebp+5], 69	; 00000045H
	mov	BYTE PTR _shellexecute_func$[ebp+6], 120 ; 00000078H
	mov	BYTE PTR _shellexecute_func$[ebp+7], 101 ; 00000065H
	mov	BYTE PTR _shellexecute_func$[ebp+8], 99	; 00000063H
	mov	BYTE PTR _shellexecute_func$[ebp+9], 117 ; 00000075H
	mov	BYTE PTR _shellexecute_func$[ebp+10], 116 ; 00000074H
	mov	BYTE PTR _shellexecute_func$[ebp+11], 101 ; 00000065H
	mov	BYTE PTR _shellexecute_func$[ebp+12], 87 ; 00000057H
	mov	BYTE PTR _shellexecute_func$[ebp+13], 0
; Line 25
	mov	BYTE PTR _notepad$[ebp], 110		; 0000006eH
	mov	BYTE PTR _notepad$[ebp+1], 111		; 0000006fH
	mov	BYTE PTR _notepad$[ebp+2], 116		; 00000074H
	mov	BYTE PTR _notepad$[ebp+3], 101		; 00000065H
	mov	BYTE PTR _notepad$[ebp+4], 112		; 00000070H
	mov	BYTE PTR _notepad$[ebp+5], 97		; 00000061H
	mov	BYTE PTR _notepad$[ebp+6], 100		; 00000064H
	mov	BYTE PTR _notepad$[ebp+7], 0
; Line 27
	mov	ecx, 72					; 00000048H
	mov	WORD PTR _msg_text$[ebp], cx
	mov	edx, 105				; 00000069H
	mov	WORD PTR _msg_text$[ebp+2], dx
	xor	eax, eax
	mov	WORD PTR _msg_text$[ebp+4], ax
; Line 28
	mov	ecx, 84					; 00000054H
	mov	WORD PTR _title_text$[ebp], cx
	mov	edx, 101				; 00000065H
	mov	WORD PTR _title_text$[ebp+2], dx
	mov	eax, 115				; 00000073H
	mov	WORD PTR _title_text$[ebp+4], ax
	mov	ecx, 116				; 00000074H
	mov	WORD PTR _title_text$[ebp+6], cx
	xor	edx, edx
	mov	WORD PTR _title_text$[ebp+8], dx
; Line 30
	lea	eax, DWORD PTR _k32_dll$[ebp]
	push	eax
	call	?get_module_by_name@@YAPAXPA_W@Z	; get_module_by_name
	add	esp, 4
	mov	DWORD PTR _kernel32_base$[ebp], eax
; Line 31
	cmp	DWORD PTR _kernel32_base$[ebp], 0
	jne	SHORT $LN2@main
; Line 32
	mov	eax, 1
	jmp	$LN1@main
$LN2@main:
; Line 35
	lea	ecx, DWORD PTR _load_lib$[ebp]
	push	ecx
	mov	edx, DWORD PTR _kernel32_base$[ebp]
	push	edx
	call	?get_func_by_name@@YAPAXPAXPAD@Z	; get_func_by_name
	add	esp, 8
	mov	DWORD PTR __LoadLibraryA$[ebp], eax
; Line 36
	lea	eax, DWORD PTR _get_proc$[ebp]
	push	eax
	mov	ecx, DWORD PTR _kernel32_base$[ebp]
	push	ecx
	call	?get_func_by_name@@YAPAXPAXPAD@Z	; get_func_by_name
	add	esp, 8
	mov	DWORD PTR __GetProcAddress$[ebp], eax
; Line 37
	cmp	DWORD PTR __LoadLibraryA$[ebp], 0
	je	SHORT $LN4@main
	cmp	DWORD PTR __GetProcAddress$[ebp], 0
	jne	SHORT $LN3@main
$LN4@main:
; Line 38
	mov	eax, 2
	jmp	$LN1@main
$LN3@main:
; Line 41
	lea	edx, DWORD PTR _u32_dll$[ebp]
	push	edx
	call	DWORD PTR __LoadLibraryA$[ebp]
	mov	DWORD PTR _user32_base$[ebp], eax
; Line 42
	cmp	DWORD PTR _user32_base$[ebp], 0
	jne	SHORT $LN5@main
; Line 43
	mov	eax, 5
	jmp	$LN1@main
$LN5@main:
; Line 46
	lea	eax, DWORD PTR _msgboxw_func$[ebp]
	push	eax
	mov	ecx, DWORD PTR _user32_base$[ebp]
	push	ecx
	call	DWORD PTR __GetProcAddress$[ebp]
	mov	DWORD PTR __MessageBoxW$[ebp], eax
; Line 47
	cmp	DWORD PTR __MessageBoxW$[ebp], 0
	jne	SHORT $LN6@main
; Line 48
	mov	eax, 6
	jmp	SHORT $LN1@main
$LN6@main:
; Line 51
	lea	edx, DWORD PTR _u32_dll$[ebp]
	push	edx
	call	DWORD PTR __LoadLibraryA$[ebp]
	mov	DWORD PTR _shell32_base$[ebp], eax
; Line 52
	cmp	DWORD PTR _shell32_base$[ebp], 0
	jne	SHORT $LN7@main
; Line 53
	mov	eax, 7
	jmp	SHORT $LN1@main
$LN7@main:
; Line 56
	lea	eax, DWORD PTR _msvcrt_dll$[ebp]
	push	eax
	call	DWORD PTR __LoadLibraryA$[ebp]
	mov	DWORD PTR _msvcrt_base$[ebp], eax
; Line 57
	cmp	DWORD PTR _msvcrt_base$[ebp], 0
	jne	SHORT $LN8@main
; Line 58
	mov	eax, 3
	jmp	SHORT $LN1@main
$LN8@main:
; Line 61
	push	64					; 00000040H
	lea	ecx, DWORD PTR _title_text$[ebp]
	push	ecx
	lea	edx, DWORD PTR _msg_text$[ebp]
	push	edx
	push	0
	call	DWORD PTR __MessageBoxW$[ebp]
	mov	DWORD PTR _msgBoxID$[ebp], eax
; Line 63
	lea	eax, DWORD PTR _system_func$[ebp]
	push	eax
	mov	ecx, DWORD PTR _msvcrt_base$[ebp]
	push	ecx
	call	DWORD PTR __GetProcAddress$[ebp]
	mov	DWORD PTR __system$[ebp], eax
; Line 65
	cmp	DWORD PTR _msgBoxID$[ebp], 1
	jne	SHORT $LN9@main
; Line 66
	lea	edx, DWORD PTR _notepad$[ebp]
	push	edx
	call	DWORD PTR __system$[ebp]
	add	esp, 4
$LN9@main:
; Line 69
	xor	eax, eax
$LN1@main:
; Line 70
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?get_func_by_name@@YAPAXPAXPAD@Z
_TEXT	SEGMENT
_funcRVA$1 = -60					; size = 4
_nameRVA$2 = -56					; size = 4
_nameIndex$3 = -52					; size = 4
_funcsListRVA$ = -48					; size = 4
_namesOrdsListRVA$ = -44				; size = 4
_funcNamesListRVA$ = -40				; size = 4
_namesCount$ = -36					; size = 4
_expAddr$ = -32						; size = 4
_nt_headers$ = -28					; size = 4
_exportsDir$ = -24					; size = 4
_idh$ = -20						; size = 4
_curr_name$4 = -16					; size = 4
_exp$ = -12						; size = 4
_i$5 = -8						; size = 4
_k$6 = -4						; size = 4
_module$ = 8						; size = 4
_func_name$ = 12					; size = 4
?get_func_by_name@@YAPAXPAXPAD@Z PROC			; get_func_by_name, COMDAT
; File C:\Users\Vova\source\repos\RGZ_ABC\peb_lookup.h
; Line 67
	push	ebp
	mov	ebp, esp
	sub	esp, 60					; 0000003cH
; Line 68
	mov	eax, DWORD PTR _module$[ebp]
	mov	DWORD PTR _idh$[ebp], eax
; Line 69
	mov	ecx, DWORD PTR _idh$[ebp]
	movzx	edx, WORD PTR [ecx]
	cmp	edx, 23117				; 00005a4dH
	je	SHORT $LN8@get_func_b
; Line 70
	xor	eax, eax
	jmp	$LN1@get_func_b
$LN8@get_func_b:
; Line 72
	mov	eax, DWORD PTR _idh$[ebp]
	mov	ecx, DWORD PTR _module$[ebp]
	add	ecx, DWORD PTR [eax+60]
	mov	DWORD PTR _nt_headers$[ebp], ecx
; Line 73
	mov	edx, 8
	imul	eax, edx, 0
	mov	ecx, DWORD PTR _nt_headers$[ebp]
	lea	edx, DWORD PTR [ecx+eax+120]
	mov	DWORD PTR _exportsDir$[ebp], edx
; Line 74
	mov	eax, DWORD PTR _exportsDir$[ebp]
	cmp	DWORD PTR [eax], 0
	jne	SHORT $LN9@get_func_b
; Line 75
	xor	eax, eax
	jmp	$LN1@get_func_b
$LN9@get_func_b:
; Line 78
	mov	ecx, DWORD PTR _exportsDir$[ebp]
	mov	edx, DWORD PTR [ecx]
	mov	DWORD PTR _expAddr$[ebp], edx
; Line 79
	mov	eax, DWORD PTR _expAddr$[ebp]
	add	eax, DWORD PTR _module$[ebp]
	mov	DWORD PTR _exp$[ebp], eax
; Line 80
	mov	ecx, DWORD PTR _exp$[ebp]
	mov	edx, DWORD PTR [ecx+24]
	mov	DWORD PTR _namesCount$[ebp], edx
; Line 82
	mov	eax, DWORD PTR _exp$[ebp]
	mov	ecx, DWORD PTR [eax+28]
	mov	DWORD PTR _funcsListRVA$[ebp], ecx
; Line 83
	mov	edx, DWORD PTR _exp$[ebp]
	mov	eax, DWORD PTR [edx+32]
	mov	DWORD PTR _funcNamesListRVA$[ebp], eax
; Line 84
	mov	ecx, DWORD PTR _exp$[ebp]
	mov	edx, DWORD PTR [ecx+36]
	mov	DWORD PTR _namesOrdsListRVA$[ebp], edx
; Line 87
	mov	DWORD PTR _i$5[ebp], 0
	jmp	SHORT $LN4@get_func_b
$LN2@get_func_b:
	mov	eax, DWORD PTR _i$5[ebp]
	add	eax, 1
	mov	DWORD PTR _i$5[ebp], eax
$LN4@get_func_b:
	mov	ecx, DWORD PTR _i$5[ebp]
	cmp	ecx, DWORD PTR _namesCount$[ebp]
	jae	$LN3@get_func_b
; Line 88
	mov	edx, DWORD PTR _module$[ebp]
	add	edx, DWORD PTR _funcNamesListRVA$[ebp]
	mov	eax, DWORD PTR _i$5[ebp]
	lea	ecx, DWORD PTR [edx+eax*4]
	mov	DWORD PTR _nameRVA$2[ebp], ecx
; Line 89
	mov	edx, DWORD PTR _module$[ebp]
	add	edx, DWORD PTR _namesOrdsListRVA$[ebp]
	mov	eax, DWORD PTR _i$5[ebp]
	lea	ecx, DWORD PTR [edx+eax*2]
	mov	DWORD PTR _nameIndex$3[ebp], ecx
; Line 90
	mov	edx, DWORD PTR _module$[ebp]
	add	edx, DWORD PTR _funcsListRVA$[ebp]
	mov	eax, DWORD PTR _nameIndex$3[ebp]
	movzx	ecx, WORD PTR [eax]
	lea	edx, DWORD PTR [edx+ecx*4]
	mov	DWORD PTR _funcRVA$1[ebp], edx
; Line 92
	mov	eax, DWORD PTR _nameRVA$2[ebp]
	mov	ecx, DWORD PTR _module$[ebp]
	add	ecx, DWORD PTR [eax]
	mov	DWORD PTR _curr_name$4[ebp], ecx
; Line 94
	mov	DWORD PTR _k$6[ebp], 0
	jmp	SHORT $LN7@get_func_b
$LN5@get_func_b:
	mov	edx, DWORD PTR _k$6[ebp]
	add	edx, 1
	mov	DWORD PTR _k$6[ebp], edx
$LN7@get_func_b:
	mov	eax, DWORD PTR _func_name$[ebp]
	add	eax, DWORD PTR _k$6[ebp]
	movsx	ecx, BYTE PTR [eax]
	test	ecx, ecx
	je	SHORT $LN6@get_func_b
	mov	edx, DWORD PTR _curr_name$4[ebp]
	add	edx, DWORD PTR _k$6[ebp]
	movsx	eax, BYTE PTR [edx]
	test	eax, eax
	je	SHORT $LN6@get_func_b
; Line 95
	mov	ecx, DWORD PTR _func_name$[ebp]
	add	ecx, DWORD PTR _k$6[ebp]
	movsx	edx, BYTE PTR [ecx]
	mov	eax, DWORD PTR _curr_name$4[ebp]
	add	eax, DWORD PTR _k$6[ebp]
	movsx	ecx, BYTE PTR [eax]
	cmp	edx, ecx
	je	SHORT $LN10@get_func_b
	jmp	SHORT $LN6@get_func_b
$LN10@get_func_b:
; Line 96
	jmp	SHORT $LN5@get_func_b
$LN6@get_func_b:
; Line 97
	mov	edx, DWORD PTR _func_name$[ebp]
	add	edx, DWORD PTR _k$6[ebp]
	movsx	eax, BYTE PTR [edx]
	test	eax, eax
	jne	SHORT $LN11@get_func_b
	mov	ecx, DWORD PTR _curr_name$4[ebp]
	add	ecx, DWORD PTR _k$6[ebp]
	movsx	edx, BYTE PTR [ecx]
	test	edx, edx
	jne	SHORT $LN11@get_func_b
; Line 99
	mov	eax, DWORD PTR _funcRVA$1[ebp]
	mov	ecx, DWORD PTR _module$[ebp]
	add	ecx, DWORD PTR [eax]
	mov	eax, ecx
	jmp	SHORT $LN1@get_func_b
$LN11@get_func_b:
; Line 101
	jmp	$LN2@get_func_b
$LN3@get_func_b:
; Line 102
	xor	eax, eax
$LN1@get_func_b:
; Line 103
	mov	esp, ebp
	pop	ebp
	ret	0
?get_func_by_name@@YAPAXPAXPAD@Z ENDP			; get_func_by_name
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?get_module_by_name@@YAPAXPA_W@Z
_TEXT	SEGMENT
_ldr$ = -48						; size = 4
_peb$ = -44						; size = 4
tv156 = -40						; size = 4
tv137 = -36						; size = 4
_head$ = -32						; size = 4
_current$1 = -28					; size = 4
_entry$2 = -24						; size = 4
_curr_name$3 = -20					; size = 4
_i$4 = -16						; size = 4
_c2$5 = -12						; size = 2
_c1$6 = -8						; size = 2
tv160 = -4						; size = 2
tv141 = -2						; size = 2
_module_name$ = 8					; size = 4
?get_module_by_name@@YAPAXPA_W@Z PROC			; get_module_by_name, COMDAT
; File C:\Users\Vova\source\repos\RGZ_ABC\peb_lookup.h
; Line 29
	push	ebp
	mov	ebp, esp
	sub	esp, 48					; 00000030H
; Line 34
	mov	eax, DWORD PTR fs:48
	mov	DWORD PTR _peb$[ebp], eax
; Line 36
	mov	ecx, DWORD PTR _peb$[ebp]
	mov	edx, DWORD PTR [ecx+12]
	mov	DWORD PTR _ldr$[ebp], edx
; Line 38
	mov	eax, DWORD PTR _ldr$[ebp]
	add	eax, 20					; 00000014H
	mov	DWORD PTR _head$[ebp], eax
; Line 39
	mov	ecx, DWORD PTR _head$[ebp]
	mov	edx, DWORD PTR [ecx]
	mov	DWORD PTR _current$1[ebp], edx
	jmp	SHORT $LN4@get_module
$LN2@get_module:
	mov	eax, DWORD PTR _current$1[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _current$1[ebp], ecx
$LN4@get_module:
	mov	edx, DWORD PTR _current$1[ebp]
	cmp	edx, DWORD PTR _head$[ebp]
	je	$LN3@get_module
; Line 40
	mov	eax, DWORD PTR _current$1[ebp]
	sub	eax, 8
	mov	DWORD PTR _entry$2[ebp], eax
; Line 41
	je	SHORT $LN9@get_module
	mov	ecx, DWORD PTR _entry$2[ebp]
	cmp	DWORD PTR [ecx+24], 0
	jne	SHORT $LN8@get_module
$LN9@get_module:
	jmp	$LN3@get_module
$LN8@get_module:
; Line 43
	mov	edx, DWORD PTR _entry$2[ebp]
	mov	eax, DWORD PTR [edx+48]
	mov	DWORD PTR _curr_name$3[ebp], eax
; Line 44
	cmp	DWORD PTR _curr_name$3[ebp], 0
	jne	SHORT $LN10@get_module
	jmp	SHORT $LN2@get_module
$LN10@get_module:
; Line 47
	mov	DWORD PTR _i$4[ebp], 0
	jmp	SHORT $LN7@get_module
$LN5@get_module:
	mov	ecx, DWORD PTR _i$4[ebp]
	add	ecx, 1
	mov	DWORD PTR _i$4[ebp], ecx
$LN7@get_module:
	mov	edx, DWORD PTR _entry$2[ebp]
	movzx	eax, WORD PTR [edx+44]
	cmp	DWORD PTR _i$4[ebp], eax
	jae	$LN6@get_module
; Line 49
	mov	ecx, DWORD PTR _i$4[ebp]
	mov	edx, DWORD PTR _module_name$[ebp]
	movzx	eax, WORD PTR [edx+ecx*2]
	test	eax, eax
	je	SHORT $LN12@get_module
	mov	ecx, DWORD PTR _i$4[ebp]
	mov	edx, DWORD PTR _curr_name$3[ebp]
	movzx	eax, WORD PTR [edx+ecx*2]
	test	eax, eax
	jne	SHORT $LN11@get_module
$LN12@get_module:
; Line 50
	jmp	$LN6@get_module
$LN11@get_module:
; Line 53
	mov	ecx, DWORD PTR _i$4[ebp]
	mov	edx, DWORD PTR _module_name$[ebp]
	movzx	eax, WORD PTR [edx+ecx*2]
	cmp	eax, 90					; 0000005aH
	jg	SHORT $LN16@get_module
	mov	ecx, DWORD PTR _i$4[ebp]
	mov	edx, DWORD PTR _module_name$[ebp]
	movzx	eax, WORD PTR [edx+ecx*2]
	cmp	eax, 65					; 00000041H
	jl	SHORT $LN16@get_module
	mov	ecx, DWORD PTR _i$4[ebp]
	mov	edx, DWORD PTR _module_name$[ebp]
	movzx	eax, WORD PTR [edx+ecx*2]
	add	eax, 32					; 00000020H
	mov	DWORD PTR tv137[ebp], eax
	mov	ecx, DWORD PTR _i$4[ebp]
	mov	edx, DWORD PTR _module_name$[ebp]
	mov	ax, WORD PTR tv137[ebp]
	mov	WORD PTR [edx+ecx*2], ax
	mov	cx, WORD PTR tv137[ebp]
	mov	WORD PTR tv141[ebp], cx
	jmp	SHORT $LN17@get_module
$LN16@get_module:
	mov	edx, DWORD PTR _i$4[ebp]
	mov	eax, DWORD PTR _module_name$[ebp]
	mov	cx, WORD PTR [eax+edx*2]
	mov	WORD PTR tv141[ebp], cx
$LN17@get_module:
	mov	dx, WORD PTR tv141[ebp]
	mov	WORD PTR _c1$6[ebp], dx
; Line 54
	mov	eax, DWORD PTR _i$4[ebp]
	mov	ecx, DWORD PTR _curr_name$3[ebp]
	movzx	edx, WORD PTR [ecx+eax*2]
	cmp	edx, 90					; 0000005aH
	jg	SHORT $LN18@get_module
	mov	eax, DWORD PTR _i$4[ebp]
	mov	ecx, DWORD PTR _curr_name$3[ebp]
	movzx	edx, WORD PTR [ecx+eax*2]
	cmp	edx, 65					; 00000041H
	jl	SHORT $LN18@get_module
	mov	eax, DWORD PTR _i$4[ebp]
	mov	ecx, DWORD PTR _curr_name$3[ebp]
	movzx	edx, WORD PTR [ecx+eax*2]
	add	edx, 32					; 00000020H
	mov	DWORD PTR tv156[ebp], edx
	mov	eax, DWORD PTR _i$4[ebp]
	mov	ecx, DWORD PTR _curr_name$3[ebp]
	mov	dx, WORD PTR tv156[ebp]
	mov	WORD PTR [ecx+eax*2], dx
	mov	ax, WORD PTR tv156[ebp]
	mov	WORD PTR tv160[ebp], ax
	jmp	SHORT $LN19@get_module
$LN18@get_module:
	mov	ecx, DWORD PTR _i$4[ebp]
	mov	edx, DWORD PTR _curr_name$3[ebp]
	mov	ax, WORD PTR [edx+ecx*2]
	mov	WORD PTR tv160[ebp], ax
$LN19@get_module:
	mov	cx, WORD PTR tv160[ebp]
	mov	WORD PTR _c2$5[ebp], cx
; Line 55
	movzx	edx, WORD PTR _c1$6[ebp]
	movzx	eax, WORD PTR _c2$5[ebp]
	cmp	edx, eax
	je	SHORT $LN13@get_module
	jmp	SHORT $LN6@get_module
$LN13@get_module:
; Line 56
	jmp	$LN5@get_module
$LN6@get_module:
; Line 58
	mov	ecx, DWORD PTR _i$4[ebp]
	mov	edx, DWORD PTR _module_name$[ebp]
	movzx	eax, WORD PTR [edx+ecx*2]
	test	eax, eax
	jne	SHORT $LN14@get_module
	mov	ecx, DWORD PTR _i$4[ebp]
	mov	edx, DWORD PTR _curr_name$3[ebp]
	movzx	eax, WORD PTR [edx+ecx*2]
	test	eax, eax
	jne	SHORT $LN14@get_module
; Line 59
	mov	ecx, DWORD PTR _entry$2[ebp]
	mov	eax, DWORD PTR [ecx+24]
	jmp	SHORT $LN1@get_module
$LN14@get_module:
; Line 61
	jmp	$LN2@get_module
$LN3@get_module:
; Line 63
	xor	eax, eax
$LN1@get_module:
; Line 64
	mov	esp, ebp
	pop	ebp
	ret	0
?get_module_by_name@@YAPAXPA_W@Z ENDP			; get_module_by_name
_TEXT	ENDS
END
